name: Branch Restriction

on:
  create:
    branches:
      - '*'
  push:
    branches:
      - '*'

jobs:
  restrict-branch-creation:
    runs-on: ubuntu-latest
    steps:
      - name: Check branch creation
        env:
          BRANCH_NAME: ${{ github.ref }}
        run: |
          ALLOWED_BRANCHES=("main" "develop")
          BRANCH_NAME=${BRANCH_NAME#refs/heads/}
          if [[ " ${ALLOWED_BRANCHES[@]} " =~ " ${BRANCH_NAME} " ]]; then
            exit 0
          else
            echo "Branch creation from $BRANCH_NAME is not allowed."
            exit 1
          fi
